insert into location (state, city, zip, street, street_num) values ('TX', 'Lubbock', '79415', 'Acker', '40');
insert into location (state, city, zip, street, street_num) values ('FL', 'Ocala', '34474', 'Riverside', '092');
insert into location (state, city, zip, street, street_num) values ('DC', 'Washington', '20051', 'Village', '29548');
insert into location (state, city, zip, street, street_num) values ('TN', 'Chattanooga', '37405', 'Oak', '1');
insert into location (state, city, zip, street, street_num) values ('MO', 'Independence', '64054', 'Harper', '07');
insert into location (city, state, zip, street, street_num) values ('Houston', 'Texas', '77201', 'Mifflin', '10');
insert into location (city, state, zip, street, street_num) values ('Newport Beach', 'California', '92662', 'Sachtjen', '21055');
insert into location (city, state, zip, street, street_num) values ('San Antonio', 'Texas', '78235', 'Oriole', '55');
insert into location (city, state, zip, street, street_num) values ('Louisville', 'Kentucky', '40280', 'Northport', '014');
insert into location (city, state, zip, street, street_num) values ('Rockford', 'Illinois', '61110', 'Commercial', '837');
insert into location (city, state, zip, street, street_num) values ('Roanoke', 'Virginia', '24040', 'Sullivan', '02');
insert into location (city, state, zip, street, street_num) values ('Saint Petersburg', 'Florida', '33742', 'Banding', '8535');
insert into location (city, state, zip, street, street_num) values ('Young America', 'Minnesota', '55573', 'Ridgeview', '90');
insert into location (city, state, zip, street, street_num) values ('Boise', 'Idaho', '83732', 'Westend', '104');
insert into location (city, state, zip, street, street_num) values ('Garland', 'Texas', '75049', 'Drewry', '4');
insert into location (city, state, zip, street, street_num) values ('Indianapolis', 'Indiana', '46202', 'Eagle Crest', '3092');
insert into location (city, state, zip, street, street_num) values ('Fresno', 'California', '93726', 'Florence', '6');
insert into location (city, state, zip, street, street_num) values ('Shawnee Mission', 'Kansas', '66276', 'Tennessee', '448');
insert into location (city, state, zip, street, street_num) values ('Glendale', 'California', '91205', 'Bonner', '8');
insert into location (city, state, zip, street, street_num) values ('Kansas City', 'Missouri', '64149', 'Fair Oaks', '65');
insert into location (city, state, zip, street, street_num) values ('San Francisco', 'California', '94177', 'Eagan', '99500');
insert into location (city, state, zip, street, street_num) values ('Corpus Christi', 'Texas', '78415', 'Dakota', '88206');
insert into location (city, state, zip, street, street_num) values ('Virginia Beach', 'Virginia', '23454', 'Northwestern', '50');
insert into location (city, state, zip, street, street_num) values ('Denver', 'Colorado', '80223', 'Hauk', '7');
insert into location (city, state, zip, street, street_num) values ('Paterson', 'New Jersey', '07522', 'John Wall', '3');
insert into location (city, state, zip, street, street_num) values ('Van Nuys', 'California', '91406', 'Sundown', '7');
insert into location (city, state, zip, street, street_num) values ('Cleveland', 'Ohio', '44130', 'Namekagon', '78');
insert into location (city, state, zip, street, street_num) values ('Orlando', 'Florida', '32854', 'Red Cloud', '53511');
insert into location (city, state, zip, street, street_num) values ('Jacksonville', 'Florida', '32255', 'Saint Paul', '85877');
insert into location (city, state, zip, street, street_num) values ('Washington', 'District of Columbia', '20073', 'Annamark', '57515');
insert into location (city, state, zip, street, street_num) values ('Jamaica', 'New York', '11407', 'Victoria', '2065');
insert into location (city, state, zip, street, street_num) values ('Santa Fe', 'New Mexico', '87505', 'Merry', '7');
insert into location (city, state, zip, street, street_num) values ('Orlando', 'Florida', '32885', 'Mayfield', '64853');
insert into location (city, state, zip, street, street_num) values ('Colorado Springs', 'Colorado', '80930', 'Colorado', '47314');
insert into location (city, state, zip, street, street_num) values ('Monticello', 'Minnesota', '55590', 'Springs', '605');
insert into location (city, state, zip, street, street_num) values ('Birmingham', 'Alabama', '35236', 'Hauk', '430');
insert into location (city, state, zip, street, street_num) values ('Sioux City', 'Iowa', '51110', 'Dapin', '7');
insert into location (city, state, zip, street, street_num) values ('Houston', 'Texas', '77020', 'Independence', '9901');
insert into location (city, state, zip, street, street_num) values ('Lansing', 'Michigan', '48930', 'Forster', '985');
insert into location (city, state, zip, street, street_num) values ('Memphis', 'Tennessee', '38104', 'Bluejay', '7');
insert into location (city, state, zip, street, street_num) values ('North Las Vegas', 'Nevada', '89087', 'Sugar', '4');
insert into location (city, state, zip, street, street_num) values ('Atlanta', 'Georgia', '30392', 'Jenna', '84');
insert into location (city, state, zip, street, street_num) values ('Brockton', 'Massachusetts', '02305', 'Corscot', '3207');
insert into location (city, state, zip, street, street_num) values ('Port Washington', 'New York', '11054', 'Meadow Valley', '3573');
insert into location (city, state, zip, street, street_num) values ('Pasadena', 'California', '91125', 'Manitowish', '57');
insert into location (city, state, zip, street, street_num) values ('Cleveland', 'Ohio', '44191', '7th', '4373');
insert into location (city, state, zip, street, street_num) values ('Little Rock', 'Arkansas', '72204', 'Crescent Oaks', '60047');
insert into location (city, state, zip, street, street_num) values ('Roanoke', 'Virginia', '24040', 'Continental', '17315');
insert into location (city, state, zip, street, street_num) values ('Oklahoma City', 'Oklahoma', '73157', 'Steensland', '889');
insert into location (city, state, zip, street, street_num) values ('Houston', 'Texas', '77070', 'Bonner', '028');
insert into location (city, state, zip, street, street_num) values ('Detroit', 'Michigan', '48267', 'Farragut', '610');
insert into location (city, state, zip, street, street_num) values ('Madison', 'Wisconsin', '53726', 'Dayton', '585');
insert into location (city, state, zip, street, street_num) values ('Seattle', 'Washington', '98175', '6th', '09');
insert into location (city, state, zip, street, street_num) values ('Colorado Springs', 'Colorado', '80925', 'Rusk', '2271');
insert into location (city, state, zip, street, street_num) values ('Lexington', 'Kentucky', '40524', 'Eagle Crest', '5');
